using HlslDecompiler.Hlsl;
using HlslDecompiler.DirectXShaderModel;
using NUnit.Framework;
using System.IO;

namespace HlslDecompiler.Tests;

[TestFixture]
// Every case is independent: it reads one .fxc, writes its output under a path
// named after its profile and shader, and shares nothing with the others.
[Parallelizable(ParallelScope.All)]
public class DecompileDxbcTests
{
    [TestCase("ps_4_0", "conditional")]
    [TestCase("ps_4_0", "duplicated_component")]
    [TestCase("ps_4_0", "constant")]
    [TestCase("ps_4_0", "constant_struct")]
    [TestCase("ps_4_0", "dot_product2_add")]
    [TestCase("ps_4_0", "derivative")]
    [TestCase("ps_4_0", "texcoord")]
    [TestCase("ps_4_0", "texcoord_modifier")]
    [TestCase("ps_4_0", "texcoord_swizzle")]
    [TestCase("ps_4_0", "float4_construct")]
    [TestCase("ps_4_0", "float4_construct2")]
    [TestCase("ps_4_0", "float4_constant")]
    [TestCase("ps_4_0", "multiply_negate")]
    [TestCase("ps_4_0", "multiply_subtract")]
    [TestCase("ps_4_0", "absolute_multiply")]
    [TestCase("ps_4_0", "negate_absolute")]
    [TestCase("ps_4_0", "sample_2d")]
    [TestCase("ps_4_0", "sample_level")]
    [TestCase("ps_4_0", "sample_grad")]
    [TestCase("ps_4_0", "sample_bias")]
    [TestCase("ps_4_0", "sample_cmp")]
    [TestCase("ps_4_0", "sample_2d_swizzle")]
    [TestCase("ps_4_0", "sample_2d_two_samplers")]
    [TestCase("ps_4_0", "clip")]
    [TestCase("ps_4_0", "clip_alpha")]
    [TestCase("ps_4_0", "clip_loop")]
    [TestCase("ps_4_0", "clip_flag")]
    [TestCase("ps_4_0", "interpolation")]
    [TestCase("ps_4_0", "int_divide")]
    [TestCase("ps_4_0", "integer_hash")]
    [TestCase("ps_4_0", "packed_scalar")]
    [TestCase("ps_4_0", "reflect_cube")]
    [TestCase("ps_4_0", "resource_swizzle")]
    [TestCase("ps_4_0", "sample_two_coordinates")]
    [TestCase("ps_4_0", "immediate_constant_buffer")]
    [TestCase("ps_4_0", "immediate_buffer_rows")]
    [TestCase("ps_4_0", "uint_convert")]
    [TestCase("ps_4_0", "do_while")]
    [TestCase("ps_4_0", "switch_case_loop")]
    [TestCase("ps_4_0", "depth_output")]
    [TestCase("ps_4_0", "conditional_return")]
    [TestCase("ps_4_0", "return_struct_early")]
    [TestCase("ps_4_0", "struct_cbuffer")]
    [TestCase("ps_4_0", "sample_offset")]
    [TestCase("ps_4_0", "nested_struct")]
    [TestCase("ps_4_0", "front_face")]
    [TestCase("ps_4_0", "derivatives")]
    [TestCase("ps_4_0", "mrt_depth")]
    [TestCase("ps_4_0", "sample_variants")]
    [TestCase("ps_4_0", "indexable_temp")]
    [TestCase("ps_4_0", "indexable_temp_loop")]
    [TestCase("ps_4_0", "get_dimensions")]
    [TestCase("ps_4_0", "get_dimensions_mip")]
    [TestCase("ps_4_1", "gather")]
    [TestCase("ps_4_1", "sample_offsets")]
    [TestCase("ps_4_1", "multisample")]
    [TestCase("ps_4_1", "decal_blend")]
    [TestCase("ps_4_0", "branch_flag")]
    [TestCase("ps_4_1", "sample_modifier")]
    [TestCase("ps_4_1", "sample_index")]
    [TestCase("ps_4_1", "cascade_shadow")]
    [TestCase("ps_4_1", "cube_array_probe")]
    [TestCase("ps_4_1", "coverage_mask")]
    [TestCase("ps_4_1", "alpha_to_coverage")]
    [TestCase("ps_4_1", "level_of_detail")]
    [TestCase("ps_4_1", "sample_count")]
    [TestCase("ps_4_1", "multisample_array")]
    [TestCase("ps_4_1", "interpolation_combined")]
    [TestCase("ps_4_0", "cbuffer_array")]
    [TestCase("ps_4_0", "uint_loop")]
    [TestCase("ps_4_0", "if_deep_nest")]
    [TestCase("ps_4_0", "texture_array")]
    [TestCase("ps_4_0", "dxbc_loop")]
    [TestCase("ps_4_0", "dxbc_continue")]
    [TestCase("ps_4_0", "switch_nested")]
    [TestCase("ps_4_0", "switch_branch")]
    [TestCase("ps_4_0", "switch_labels")]
    [TestCase("ps_4_0", "dxbc_switch")]
    [TestCase("ps_4_0", "early_return")]
    [TestCase("ps_4_0", "divide")]
    [TestCase("ps_4_0", "compare")]
    [TestCase("ps_4_0", "rounding")]
    [TestCase("ps_4_0", "logical_and")]
    [TestCase("ps_4_0", "saturate_step")]
    [TestCase("ps_4_0", "packed_cbuffer")]
    [TestCase("ps_4_0", "packed_interpolator")]
    [TestCase("ps_4_0", "shadow_pcf")]
    [TestCase("ps_4_0", "march_return")]
    [TestCase("ps_4_0", "loop_continue_acc")]
    [TestCase("ps_4_0", "nested_break")]
    [TestCase("ps_4_0", "volume_march")]
    [TestCase("ps_4_0", "half_packing")]
    [TestCase("ps_4_0", "ambient_occlusion")]
    [TestCase("ps_4_0", "colour_grade")]
    [TestCase("ps_4_0", "parallax_occlusion")]
    [TestCase("ps_4_0", "gbuffer_decode")]
    [TestCase("ps_4_0", "step_mask")]
    [TestCase("ps_4_0", "sign_intrinsic")]
    [TestCase("ps_4_0", "integer_vector")]
    [TestCase("ps_4_0", "comparison_mask")]
    [TestCase("ps_4_0", "equality_select")]
    [TestCase("ps_4_0", "sample_compare")]
    [TestCase("ps_5_0", "gather_compare")]
    [TestCase("ps_5_0", "gather_channels")]
    [TestCase("ps_5_0", "attribute_evaluate")]
    [TestCase("ps_5_0", "attribute_snapped")]
    [TestCase("ps_5_0", "microfacet_lighting")]
    [TestCase("ps_5_0", "occlusion_kernel")]
    [TestCase("ps_5_0", "attribute_centroid")]
    [TestCase("ps_5_0", "sample_position")]
    [TestCase("ps_5_0", "sample_position_constant")]
    [TestCase("ps_5_0", "render_target_samples")]
    [TestCase("ps_5_0", "integer_divide")]
    [TestCase("ps_5_0", "sine_cosine")]
    [TestCase("ps_5_0", "rotate_components")]
    [TestCase("ps_5_0", "swap_carried")]
    [TestCase("ps_5_0", "struct_members")]
    [TestCase("ps_5_0", "reciprocal_root")]
    [TestCase("ps_5_0", "masked_shift")]
    [TestCase("ps_5_0", "byte_packing")]
    [TestCase("ps_5_0", "texture_channels_uint")]
    [TestCase("ps_5_0", "texture_channels_sint")]
    [TestCase("ps_5_0", "integer_texture_load")]
    [TestCase("ps_5_0", "constant_packoffset")]
    [TestCase("ps_5_0", "nested_struct_members")]
    [TestCase("ps_5_0", "multisample_array_size")]
    [TestCase("vs_5_0", "matrix_array_index")]
    [TestCase("ps_5_0", "bit_fields")]
    [TestCase("ps_5_0", "tangent_lighting")]
    [TestCase("ps_5_0", "integer_target")]
    [TestCase("ps_5_0", "nested_array_cbuffer")]
    [TestCase("ps_5_0", "continue_carries_step")]
    [TestCase("ps_5_0", "struct_matrix_packing")]
    [TestCase("vs_5_0", "skinned_instances")]
    [TestCase("vs_5_0", "instance_clip")]
    [TestCase("vs_5_0", "instance_matrix_mul")]
    [TestCase("vs_5_0", "tight_packed_element")]
    [TestCase("vs_5_0", "packed_matrix_members")]
    [TestCase("vs_5_0", "row_major_instances")]
    [TestCase("cs_5_0", "tile_luminance")]
    [TestCase("cs_5_0", "prefix_flags")]
    [TestCase("ps_5_0", "depth_aware_blur")]
    [TestCase("ps_5_0", "gbuffer_write")]
    [TestCase("ps_5_0", "environment_lighting")]
    [TestCase("ps_5_0", "gather_offset")]
    [TestCase("ps_5_0", "derivative_precision")]
    [TestCase("ps_5_0", "coverage_input")]
    [TestCase("ps_5_0", "inner_coverage")]
    [TestCase("ps_5_0", "stencil_ref")]
    [TestCase("ps_5_0", "typed_view_load")]
    [TestCase("ps_5_0", "load_two_addresses")]
    [TestCase("ps_5_0", "packed_input_cross")]
    [TestCase("ps_5_0", "get_dimensions_shapes")]
    [TestCase("ps_5_0", "texture_buffer_index")]
    [TestCase("gs_5_0", "stream_expand")]
    [TestCase("gs_5_0", "cube_faces")]
    [TestCase("gs_5_0", "two_streams")]
    [TestCase("gs_5_0", "three_streams")]
    [TestCase("gs_5_0", "instanced_expand")]
    [TestCase("gs_5_0", "particle_sprites")]
    [TestCase("gs_5_0", "primitive_id_output")]
    [TestCase("ds_5_0", "patch_interpolate")]
    [TestCase("ds_5_0", "patch_constants")]
    [TestCase("ds_5_0", "quad_patch")]
    [TestCase("ds_5_0", "displaced_patch")]
    [TestCase("ds_5_0", "terrain_quad")]
    [TestCase("ds_5_0", "isoline_curve")]
    [TestCase("hs_5_0", "tri_distance")]
    [TestCase("hs_5_0", "quad_factors")]
    [TestCase("hs_5_0", "passed_through")]
    [TestCase("hs_5_0", "isoline_detail")]
    [TestCase("hs_5_0", "isoline_instanced")]
    [TestCase("hs_5_0", "instanced_factors")]
    [TestCase("hs_5_0", "culled_patch")]
    [TestCase("hs_5_0", "split_control_points")]
    [TestCase("hs_5_0", "carried_constants")]
    [TestCase("ps_4_0", "texture_load")]
    [TestCase("ps_4_0", "intrinsics")]
    [TestCase("ps_4_0", "transcend")]
    [TestCase("ps_4_0", "int_arithmetic")]
    [TestCase("ps_4_0", "int_constant_divide")]
    [TestCase("ps_4_0", "conditional_depth")]
    [TestCase("ps_4_0", "texture_1d_3d")]
    [TestCase("ps_4_0", "texture_1d_array")]
    [TestCase("ps_4_0", "texture_formats")]
    [TestCase("ps_4_0", "texture_buffer")]
    [TestCase("ps_4_0", "typed_buffer")]
    [TestCase("ps_4_0", "int_minmax")]
    [TestCase("ps_4_0", "divide_product")]
    [TestCase("ps_4_0", "subtract_sum")]
    [TestCase("ps_4_0", "bit_field")]
    [TestCase("ps_4_0", "index_and_scale")]
    [TestCase("ps_4_0", "unsigned_compare")]
    [TestCase("ps_4_0", "wide_constant")]
    [TestCase("vs_4_0", "attribute_divide")]
    [TestCase("cs_4_1", "shared_float_int_index")]
    [TestCase("ps_4_0", "mixed_register")]
    [TestCase("cs_4_0", "atomic_free_sum")]
    [TestCase("vs_4_0", "packed_colour")]
    [TestCase("ps_4_0", "precedence_mix")]
    [TestCase("ps_4_0", "int_float_mix")]
    [TestCase("ps_4_0", "sample_select")]
    [TestCase("ps_4_0", "branch_sample")]
    [TestCase("ps_4_0", "screen_position")]
    [TestCase("vs_4_0", "constant")]
    [TestCase("vs_4_0", "constant_struct")]
    [TestCase("vs_4_0", "dot_product")]
    [TestCase("vs_4_0", "length")]
    [TestCase("vs_4_0", "matrix22_vector2_multiply")]
    [TestCase("vs_4_0", "matrix23_vector2_multiply")]
    [TestCase("vs_4_0", "matrix33_vector3_multiply")]
    [TestCase("vs_4_0", "matrix34_vector4_multiply")]
    [TestCase("vs_4_0", "matrix44_vector4_multiply")]
    [TestCase("vs_4_0", "matrix_pair")]
    [TestCase("vs_4_0", "matrix_array")]
    [TestCase("vs_4_0", "shared_cbuffer")]
    [TestCase("vs_4_0", "vertex_id")]
    [TestCase("vs_4_0", "any_all")]
    [TestCase("vs_4_0", "integer_inputs")]
    [TestCase("vs_4_0", "input_array")]
    [TestCase("vs_4_0", "instance_structs")]
    [TestCase("vs_4_0", "static_struct_matrix")]
    [TestCase("vs_4_0", "single_struct_matrix")]
    [TestCase("vs_4_0", "row_major_matrix43")]
    [TestCase("vs_4_0", "matrix_member_add")]
    [TestCase("vs_4_0", "bitwise")]
    [TestCase("vs_4_0", "skinning")]
    [TestCase("vs_4_0", "skin_buffer")]
    [TestCase("vs_4_0", "particle_draw")]
    [TestCase("vs_4_0", "instance_buffer")]
    [TestCase("vs_4_0", "dynamic_index")]
    [TestCase("vs_4_0", "loop_array")]
    [TestCase("vs_4_0", "normalize")]
    [TestCase("vs_4_0", "submatrix43_vector3_multiply")]
    [TestCase("vs_4_0", "vector2_matrix22_multiply")]
    [TestCase("vs_4_0", "vector2_matrix32_multiply")]
    [TestCase("vs_4_0", "vector3_matrix33_multiply")]
    [TestCase("vs_4_0", "vector4_matrix44_multiply")]
    [TestCase("vs_4_0", "normal_transform")]
    [TestCase("vs_4_0", "clip_cull")]
    [TestCase("gs_4_1", "main")]
    [TestCase("gs_4_1", "circle")]
    [TestCase("gs_4_0", "triangle_adjacency")]
    [TestCase("gs_4_0", "triangle_passthrough")]
    [TestCase("gs_4_0", "particle_expand")]
    [TestCase("gs_4_0", "cube_shadow")]
    [TestCase("gs_4_0", "reassigned_old_and_new")]
    [TestCase("gs_4_0", "triangle_expand")]
    [TestCase("gs_4_0", "line_strip")]
    [TestCase("gs_4_0", "primitive_id")]
    [TestCase("gs_4_0", "adjacency_viewport")]
    [TestCase("gs_4_0", "billboard")]
    [TestCase("gs_4_1", "point_expand")]
    [TestCase("cs_4_1", "compute")]
    [TestCase("cs_4_1", "compute_reduce")]
    [TestCase("cs_4_1", "compute_hash")]
    [TestCase("cs_4_1", "compute_vector")]
    [TestCase("cs_4_1", "compute_loop")]
    [TestCase("cs_4_1", "integer_multiply")]
    [TestCase("cs_4_1", "groupshared_reduce")]
    [TestCase("cs_4_1", "groupshared_struct")]
    [TestCase("cs_5_0", "histogram")]
    [TestCase("cs_5_0", "groupshared_atomic")]
    [TestCase("cs_5_0", "groupshared_neighbours")]
    [TestCase("cs_5_0", "local_array_window")]
    [TestCase("cs_5_0", "groupshared_scan")]
    [TestCase("cs_5_0", "groupshared_wide")]
    [TestCase("cs_5_0", "groupshared_pair")]
    [TestCase("cs_5_0", "masked_differences")]
    [TestCase("cs_5_0", "masked_buffer_source")]
    [TestCase("cs_5_0", "masked_accumulated")]
    [TestCase("cs_5_0", "masked_zero_word")]
    [TestCase("cs_5_0", "masked_folded_source")]
    [TestCase("cs_5_0", "masked_constant_accumulator")]
    [TestCase("cs_5_0", "masked_folded_low_word")]
    [TestCase("cs_5_0", "masked_added_high_word")]
    [TestCase("cs_5_0", "structured_minmax")]
    [TestCase("cs_5_0", "signed_atomic")]
    [TestCase("cs_5_0", "atomic_counter")]
    [TestCase("cs_5_0", "texel_atomic")]
    [TestCase("cs_5_0", "texture_write")]
    [TestCase("cs_5_0", "texture_accumulate")]
    [TestCase("cs_5_0", "buffer_write")]
    [TestCase("cs_5_0", "buffer_size")]
    [TestCase("cs_5_0", "uav_dimensions")]
    [TestCase("cs_5_0", "typed_buffer_size")]
    [TestCase("cs_5_0", "append_filter")]
    [TestCase("cs_5_0", "append_consume")]
    [TestCase("cs_5_0", "append_computed")]
    [TestCase("cs_5_0", "buffer_counter")]
    [TestCase("cs_5_0", "struct_member_store")]
    [TestCase("cs_5_0", "loop_fused_step")]
    [TestCase("cs_5_0", "raw_buffer_dwords")]
    [TestCase("cs_5_0", "structured_matrix_member")]
    [TestCase("cs_5_0", "nested_struct_member")]
    [TestCase("cs_5_0", "array_member")]
    [TestCase("cs_5_0", "mixed_member_types")]
    [TestCase("cs_5_0", "struct_member_atomic")]
    [TestCase("cs_5_0", "consume_double")]
    [TestCase("cs_5_0", "consume_two_calls")]
    [TestCase("cs_5_0", "luminance_histogram")]
    [TestCase("cs_5_0", "bit_counts")]
    [TestCase("cs_5_0", "high_bit")]
    [TestCase("cs_5_0", "stored_select")]
    [TestCase("cs_5_0", "half_pack")]
    [TestCase("cs_5_0", "half_unpack")]
    [TestCase("cs_5_0", "double_precision")]
    [TestCase("cs_5_0", "double_select")]
    [TestCase("cs_5_0", "double_buffer")]
    [TestCase("cs_5_0", "double_vector_buffer")]
    [TestCase("cs_5_0", "double_struct_member")]
    [TestCase("cs_5_0", "double_nested_array")]
    [TestCase("cs_5_0", "double_mixed_struct")]
    [TestCase("ps_5_0", "double_immediate")]
    [TestCase("ps_5_0", "double_compare")]
    [TestCase("cs_4_0", "raw_buffer")]
    [TestCase("cs_4_0", "bitpack")]
    [TestCase("cs_4_0", "particle_update")]
    [TestCase("cs_4_0", "tile_blur")]
    [TestCase("ps_5_0", "duplicated_component")]
    [TestCase("ps_5_0", "broadcast_widths")]
    [TestCase("ps_5_0", "sample_position_pair")]
    [TestCase("ps_5_0", "inverse_trig")]
    [TestCase("ps_5_0", "modf_split")]
    [TestCase("ps_4_0", "modf_split")]
    [TestCase("ps_5_0", "frexp_ldexp")]
    [TestCase("ps_5_0", "special_values")]
    [TestCase("ps_5_0", "float_classify")]
    [TestCase("ps_5_0", "early_depth")]
    [TestCase("ps_5_0", "inf_select_shared")]
    [TestCase("ps_5_0", "face_forward")]
    [TestCase("ps_5_0", "refraction")]
    [TestCase("cs_5_0", "atomic_old_values")]
    [TestCase("cs_5_0", "atomic_struct_member")]
    [TestCase("cs_5_0", "atomic_compare_exchange")]
    [TestCase("cs_5_0", "typed_buffer_read")]
    [TestCase("cs_5_0", "append_buffer_size")]
    [TestCase("cs_5_0", "group_shared_counter")]
    [TestCase("cs_5_0", "byte_address_literals")]
    [TestCase("ps_5_0", "gather_cmp_variants")]
    [TestCase("ps_4_0", "vector_subscript")]
    [TestCase("ps_4_0", "float_modulo_complement")]
    [TestCase("cs_5_0", "stored_loop_counter")]
    [TestCase("cs_5_0", "branch_stored_index")]
    [TestCase("cs_5_0", "switch_stored_index")]
    [TestCase("cs_5_0", "tile_depth_bounds")]
    [TestCase("ps_5_0", "octahedral_normal")]
    [TestCase("vs_4_0", "matrix_elements")]
    [TestCase("cs_5_0", "stored_float_bits")]
    [TestCase("cs_5_0", "consume_bits_scaled")]
    [TestCase("vs_4_0", "packed_bits_uniform")]
    [TestCase("cs_4_0", "cached_texel_blur")]
    [TestCase("ps_5_0", "transposed_basis")]
    [TestCase("ps_5_0", "normal_map_basis")]
    [TestCase("ps_5_0", "matrix_row_blend")]
    [TestCase("ps_5_0", "matrix_column_blend")]
    [TestCase("cs_5_0", "struct_flags")]
    [TestCase("gs_5_0", "looped_vertices")]
    [TestCase("hs_5_0", "looped_control_points")]
    [TestCase("ps_5_0", "texture_buffer_globals")]
    [TestCase("ps_5_0", "split_transform")]
    [TestCase("cs_5_0", "asdouble_bits")]
    [TestCase("ps_5_0", "integer_targets")]
    [TestCase("hs_5_0", "quad_tess_factors")]
    [TestCase("cs_5_0", "stored_double_bits")]
    [TestCase("cs_5_0", "asdouble_bits_uniform")]
    [TestCase("cs_5_0", "consume_atomic_max")]
    [TestCase("cs_5_0", "bitonic_sort_step")]
    [TestCase("ps_5_0", "cascaded_shadows")]
    [TestCase("ps_5_0", "parallax_steps")]
    [TestCase("ps_5_0", "dynamic_linkage")]
    [TestCase("ps_5_0", "dynamic_linkage_methods")]
    public void DecompileTest(string profile, string baseFilename)
    {
        string compiledShaderFilename = $"CompiledShaders{Path.DirectorySeparatorChar}{profile}{Path.DirectorySeparatorChar}{baseFilename}.fxc";
        string asmExpectedFilename = $"ShaderAssembly{Path.DirectorySeparatorChar}{profile}{Path.DirectorySeparatorChar}{baseFilename}.asm";
        string hlslExpectedFilename = $"ShaderSources{Path.DirectorySeparatorChar}{profile}{Path.DirectorySeparatorChar}{baseFilename}.fx";
        string hlslInstructionExpectedFilename = $"ShaderSources{Path.DirectorySeparatorChar}{profile}_instruction{Path.DirectorySeparatorChar}{baseFilename}.fx";
        string asmOutputFilename = $"{profile}{Path.DirectorySeparatorChar}{baseFilename}.asm";
        string hlslOutputFilename = $"{profile}{Path.DirectorySeparatorChar}{baseFilename}.fx";
        string hlslInstructionOutputFilename = $"{profile}{Path.DirectorySeparatorChar}{baseFilename}_instruction.fx";

        ShaderModel shader;

        using var inputStream = File.Open(Path.GetFullPath(compiledShaderFilename), FileMode.Open, FileAccess.Read, FileShare.Read);
        using (var input = new DxbcReader(inputStream, true))
        {
            shader = input.ReadShader();
        }

        var asmWriter = new AsmWriter(shader);
        FileUtil.MakeFolder(asmOutputFilename);
        asmWriter.Write(asmOutputFilename);

        var hlslInstructionWriter = new HlslSimpleWriter(shader);
        FileUtil.MakeFolder(hlslInstructionOutputFilename);
        hlslInstructionWriter.Write(hlslInstructionOutputFilename);

        var hlslWriter = new HlslAstWriter(shader);
        FileUtil.MakeFolder(hlslOutputFilename);
        hlslWriter.Write(hlslOutputFilename);

        Goldens.AssertMatches(asmOutputFilename, asmExpectedFilename,
            "Assembly not equal at " + asmOutputFilename);
        Goldens.AssertMatches(hlslInstructionOutputFilename, hlslInstructionExpectedFilename,
            "HLSL not equal at " + hlslInstructionOutputFilename);
        Goldens.AssertMatches(hlslOutputFilename, hlslExpectedFilename,
            "AST HLSL not equal at " + hlslOutputFilename);
    }
}
