namespace HlslDecompiler.DirectXShaderModel;

public enum OperandType
{
    Temp,
    Input,
    Output,
    IndexableTemp,
    Immediate32,
    Immediate64,
    Sampler,
    Resource,
    ConstantBuffer,
    ImmediateConstantBuffer,
    Label,
    InputPrimitiveID,
    OutputDepth,
    Null,
    Rasterizer,
    OutputCoverageMask,
    Stream,
    FunctionBody,
    FunctionTable,
    Interface,
    FunctionInput,
    FunctionOutput,
    OutputControlPointID,
    InputForkInstanceID,
    InputJoinInstanceID,
    InputControlPoint,
    OutputControlPoint,
    InputPatchConstant,
    InputDomainPoint,
    ThisPointer,
    UnorderedAccessView,
    ThreadGroupSharedMemory,
    InputThreadID,
    InputThreadGroupID,
    InputThreadIDInGroup,
    InputCoverageMask,
    InputThreadIDInGroupFlattened,
    InputGSInstanceID,
    OutputDepthGreaterEqual,
    OutputDepthLessEqual,
    CycleCounter,
    // The stencil reference a pixel shader writes out, and the rasterizer's
    // answer to whether it covered the whole pixel. Both name one number and
    // no register, the way the coverage mask above does.
    OutputStencilRef,
    InputInnerCoverage
}
