//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// POSITION                 1   xyzw        1     NONE   float   xyzw
// POSITION                 2   xyz         2     NONE   float   xyz 
// POSITION                 3   xyz         3     NONE   float   xyz 
//
vs_4_0
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyz
dcl_output o3.xyz
mov o0.xyzw, l(0,0,0,0)
mov o1.xyzw, l(0,0,0,0)
mov o2.xyz, l(0,0,0,0)
mov o3.xyz, l(0,0,0,0)
ret 
// Approximately 5 instruction slots used
