//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
//
vs_4_0
dcl_input v0.xyz
dcl_output o0.xyzw
dcl_temps 1
dp3 r0.x, v0.xyzx, v0.xyzx
rsq r0.x, r0.x
mul o0.xyz, r0.xxxx, v0.yxzy
mov o0.w, l(1.000000)
ret 
// Approximately 5 instruction slots used
