//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float3x2 matrix_3x2;               // Offset:    0 Size:    28
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// POSITION                 1   xy          1     NONE   float   xy  
// POSITION                 2     zw        1     NONE   float     zw
//
vs_4_0
dcl_constantbuffer cb0[2], immediateIndexed
dcl_input v0.xy
dcl_output o0.xyzw
dcl_output o1.xy
dcl_output o1.zw
dcl_temps 1
dp2 o0.x, v0.xyxx, cb0[0].xyxx
dp2 o0.y, v0.xyxx, cb0[1].xyxx
dp2 o0.z, v0.yxyy, cb0[0].xyxx
dp2 o0.w, v0.yxyy, cb0[1].xyxx
dp2 o1.x, |v0.yxyy|, cb0[0].xyxx
dp2 o1.y, |v0.yxyy|, cb0[1].xyxx
add r0.xy, v0.xyxx, v0.xyxx
dp2 o1.z, r0.xyxx, cb0[0].xyxx
dp2 o1.w, r0.xyxx, cb0[1].xyxx
ret 
// Approximately 10 instruction slots used
