//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_4_0
dcl_output o0.xyzw
dcl_output o1.xyzw
mov o0.xyzw, l(0.300000,0.700000,0.010000,-50.009998)
mov o1.xyzw, l(-1234567.000000,50.009998,5.010000,0)
ret 
// Approximately 3 instruction slots used
